services:
  scanner:
    image: devfarmaan/terminal:latest-arm64
    command: [ "--mode", "api" ]
    expose:
      - 8000
    ports:
      - 8001:8000
    env_file:
      - .env
    environment:
      - OCI_BUCKET=${OCI_BUCKET}
      - OCI_CONFIG=${OCI_CONFIG}
      - OCI_KEY=${OCI_KEY}
      - BASE_FILE_PATH=/data/files
    volumes:
      - "./data/files:/data/files"
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://127.0.0.1:8000/docs" ]
    restart: unless-stopped