[project]
name = "terminal-data"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.11.18",
    "apscheduler>=3.11.0",
    "dotenv>=0.9.9",
    "duckdb>=1.3.0",
    "fastapi[standard]>=0.115.12",
    "httpx>=0.28.1",
    "loguru>=0.7.3",
    "numpy==1.26.4",
    "oci>=2.152.0",
    "ocifs>=1.3.2",
    "pandas>=2.2.3",
    "pandas-ta>=0.3.14b0",
    "pyarrow>=20.0.0",
    "pydantic>=2.11.4",
    "supabase>=2.15.1",
    "ta-lib>=0.6.3",
    "websockets>=14.2",
    "yfinance>=0.2.61",
]
