"""Add lists fk to scan sources

Revision ID: 264637f5491c
Revises: 16e34b5b3874
Create Date: 2026-02-20 14:35:28.877130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '264637f5491c'
down_revision: Union[str, Sequence[str], None] = '16e34b5b3874'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'scans', 'lists', ['sources'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scans', type_='foreignkey')
    # ### end Alembic commands ###
