"""initial_schema

Revision ID: f0d7555e9029
Revises: 
Create Date: 2026-03-11 11:33:50.404847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f0d7555e9029'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('column_sets',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('columns', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_column_sets_user_id'), 'column_sets', ['user_id'], unique=False)
    op.create_table('condition_sets',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('conditional_logic', sa.String(), nullable=False),
    sa.Column('timeframe', sa.String(), nullable=False),
    sa.Column('timeframe_value', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_condition_sets_user_id'), 'condition_sets', ['user_id'], unique=False)
    op.create_table('formulas',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_formulas_user_id'), 'formulas', ['user_id'], unique=False)
    op.create_table('lists',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('simple', 'color', 'combo', 'system', name='listtype'), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('symbols', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('source_list_ids', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lists_user_id'), 'lists', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('alerts',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('alert_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('trigger_condition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('guard_conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('frequency', sa.String(), nullable=False),
    sa.Column('frequency_interval', sa.Integer(), nullable=False),
    sa.Column('expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trigger_count', sa.Integer(), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notification_channels', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('alert_sound', sa.String(), nullable=True),
    sa.Column('drawing_id', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_drawing_id'), 'alerts', ['drawing_id'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_index(op.f('ix_alerts_symbol'), 'alerts', ['symbol'], unique=False)
    op.create_index(op.f('ix_alerts_user_id'), 'alerts', ['user_id'], unique=False)
    op.create_table('broker_credentials',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=True),
    sa.Column('account_label', sa.String(), nullable=True),
    sa.Column('account_owner', sa.String(), nullable=True),
    sa.Column('profile_raw', sa.JSON(), nullable=True),
    sa.Column('encrypted_token', sa.Text(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_broker_credentials_account_id'), 'broker_credentials', ['account_id'], unique=False)
    op.create_index(op.f('ix_broker_credentials_provider'), 'broker_credentials', ['provider'], unique=False)
    op.create_index(op.f('ix_broker_credentials_user_id'), 'broker_credentials', ['user_id'], unique=False)
    op.create_table('broker_defaults',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('capability', sa.String(), nullable=False),
    sa.Column('market', sa.String(), nullable=False),
    sa.Column('provider_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'capability', 'market', name='uq_broker_defaults_user_capability_market')
    )
    op.create_index(op.f('ix_broker_defaults_capability'), 'broker_defaults', ['capability'], unique=False)
    op.create_index(op.f('ix_broker_defaults_market'), 'broker_defaults', ['market'], unique=False)
    op.create_index(op.f('ix_broker_defaults_provider_id'), 'broker_defaults', ['provider_id'], unique=False)
    op.create_index(op.f('ix_broker_defaults_user_id'), 'broker_defaults', ['user_id'], unique=False)
    op.create_table('user_charts',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('resolution', sa.String(), nullable=True),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_charts_user_id'), 'user_charts', ['user_id'], unique=False)
    op.create_table('user_notification_channels',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('channel_type', sa.String(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_notification_channels_user_id'), 'user_notification_channels', ['user_id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('layout', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_user_preferences_user_id')
    )
    op.create_index(op.f('ix_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=False)
    op.create_table('user_study_templates',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_study_templates_user_name')
    )
    op.create_index(op.f('ix_user_study_templates_user_id'), 'user_study_templates', ['user_id'], unique=False)
    op.create_table('alert_logs',
    sa.Column('alert_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trigger_value', sa.Float(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_logs_alert_id'), 'alert_logs', ['alert_id'], unique=False)
    op.create_index(op.f('ix_alert_logs_user_id'), 'alert_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alert_logs_user_id'), table_name='alert_logs')
    op.drop_index(op.f('ix_alert_logs_alert_id'), table_name='alert_logs')
    op.drop_table('alert_logs')
    op.drop_index(op.f('ix_user_study_templates_user_id'), table_name='user_study_templates')
    op.drop_table('user_study_templates')
    op.drop_index(op.f('ix_user_preferences_user_id'), table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_user_notification_channels_user_id'), table_name='user_notification_channels')
    op.drop_table('user_notification_channels')
    op.drop_index(op.f('ix_user_charts_user_id'), table_name='user_charts')
    op.drop_table('user_charts')
    op.drop_index(op.f('ix_broker_defaults_user_id'), table_name='broker_defaults')
    op.drop_index(op.f('ix_broker_defaults_provider_id'), table_name='broker_defaults')
    op.drop_index(op.f('ix_broker_defaults_market'), table_name='broker_defaults')
    op.drop_index(op.f('ix_broker_defaults_capability'), table_name='broker_defaults')
    op.drop_table('broker_defaults')
    op.drop_index(op.f('ix_broker_credentials_user_id'), table_name='broker_credentials')
    op.drop_index(op.f('ix_broker_credentials_provider'), table_name='broker_credentials')
    op.drop_index(op.f('ix_broker_credentials_account_id'), table_name='broker_credentials')
    op.drop_table('broker_credentials')
    op.drop_index(op.f('ix_alerts_user_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_symbol'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_drawing_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_lists_user_id'), table_name='lists')
    op.drop_table('lists')
    op.drop_index(op.f('ix_formulas_user_id'), table_name='formulas')
    op.drop_table('formulas')
    op.drop_index(op.f('ix_condition_sets_user_id'), table_name='condition_sets')
    op.drop_table('condition_sets')
    op.drop_index(op.f('ix_column_sets_user_id'), table_name='column_sets')
    op.drop_table('column_sets')
    # ### end Alembic commands ###
