"""Rename condition columns

Revision ID: 16086536e80e
Revises: 264637f5491c
Create Date: 2026-02-20 16:38:23.258199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16086536e80e'
down_revision: Union[str, Sequence[str], None] = '264637f5491c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conditions', sa.Column('formula', sa.String(), nullable=False))
    op.add_column('conditions', sa.Column('true_when', sa.String(), nullable=False))
    op.add_column('conditions', sa.Column('true_when_param', sa.Integer(), nullable=True))
    op.add_column('conditions', sa.Column('type', sa.String(), nullable=False))
    op.drop_column('conditions', 'condition_type')
    op.drop_column('conditions', 'evaluated_at')
    op.drop_column('conditions', 'evaluated_at_param')
    op.drop_column('conditions', 'expr')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conditions', sa.Column('expr', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('conditions', sa.Column('evaluated_at_param', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('conditions', sa.Column('evaluated_at', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('conditions', sa.Column('condition_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('conditions', 'type')
    op.drop_column('conditions', 'true_when_param')
    op.drop_column('conditions', 'true_when')
    op.drop_column('conditions', 'formula')
    # ### end Alembic commands ###
