"""Add scan module

Revision ID: 16e34b5b3874
Revises: d15c6310a8b5
Create Date: 2026-02-20 12:28:13.251568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '16e34b5b3874'
down_revision: Union[str, Sequence[str], None] = 'd15c6310a8b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conditions',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('expr', sa.String(), nullable=False),
    sa.Column('evaluated_at', sa.String(), nullable=False),
    sa.Column('evaluated_at_param', sa.Integer(), nullable=True),
    sa.Column('evaluation_type', sa.String(), nullable=False),
    sa.Column('condition_type', sa.String(), nullable=False),
    sa.Column('rank_min', sa.Integer(), nullable=True),
    sa.Column('rank_max', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conditions_user_id'), 'conditions', ['user_id'], unique=False)
    op.create_table('scans',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sources', sa.String(), nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('conditional_logic', sa.String(), nullable=False),
    sa.Column('pre_conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pre_condition_logic', sa.String(), nullable=False),
    sa.Column('columns', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scans_user_id'), 'scans', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scans_user_id'), table_name='scans')
    op.drop_table('scans')
    op.drop_index(op.f('ix_conditions_user_id'), table_name='conditions')
    op.drop_table('conditions')
    # ### end Alembic commands ###
