"""Drop condition library table

Revision ID: c6572d102d0e
Revises: 16086536e80e
Create Date: 2026-02-20 16:46:13.669265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c6572d102d0e'
down_revision: Union[str, Sequence[str], None] = '16086536e80e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conditions_user_id'), table_name='conditions')
    op.drop_table('conditions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conditions',
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('evaluation_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('rank_min', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rank_max', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('formula', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('true_when', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('true_when_param', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('conditions_pkey'))
    )
    op.create_index(op.f('ix_conditions_user_id'), 'conditions', ['user_id'], unique=False)
    # ### end Alembic commands ###
