"""Remove pre_conditions from scan

Revision ID: 4d7b4c9f1c67
Revises: c6572d102d0e
Create Date: 2026-02-20 16:57:21.487579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4d7b4c9f1c67'
down_revision: Union[str, Sequence[str], None] = 'c6572d102d0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scans', 'pre_condition_logic')
    op.drop_column('scans', 'pre_conditions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scans', sa.Column('pre_conditions', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('scans', sa.Column('pre_condition_logic', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
