"""add candle_data_refreshes

Revision ID: fc690ed014eb
Revises: 5d6d6d8d0b2f
Create Date: 2026-03-07 22:00:46.293620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc690ed014eb'
down_revision: Union[str, Sequence[str], None] = '5d6d6d8d0b2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candle_data_refreshes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('exchange', sa.String(length=10), nullable=False),
    sa.Column('timeframe', sa.String(length=5), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('symbols_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candle_data_refreshes_exchange'), 'candle_data_refreshes', ['exchange'], unique=False)
    op.create_index(op.f('ix_candle_data_refreshes_timeframe'), 'candle_data_refreshes', ['timeframe'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candle_data_refreshes_timeframe'), table_name='candle_data_refreshes')
    op.drop_index(op.f('ix_candle_data_refreshes_exchange'), table_name='candle_data_refreshes')
    op.drop_table('candle_data_refreshes')
    # ### end Alembic commands ###
