"""add_play_sound_to_alerts

Revision ID: 1aab159d8a19
Revises: 905f6e4d32d1
Create Date: 2026-03-10 13:35:26.798287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1aab159d8a19'
down_revision: Union[str, Sequence[str], None] = '905f6e4d32d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add column as nullable first
    op.add_column('alerts', sa.Column('play_sound', sa.Boolean(), nullable=True))
    # Update existing rows
    op.execute("UPDATE alerts SET play_sound = TRUE")
    # Set NOT NULL constraint
    op.alter_column('alerts', 'play_sound', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alerts', 'play_sound')
    # ### end Alembic commands ###
