"""Add columns to lists and drop scans

Revision ID: be7919ba76d2
Revises: f865320e648b
Create Date: 2026-02-22 22:26:40.313060

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "be7919ba76d2"
down_revision: Union[str, Sequence[str], None] = "f865320e648b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "condition_sets",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "conditions", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("conditional_logic", sa.String(), nullable=False),
        sa.Column("timeframe", sa.String(), nullable=False),
        sa.Column("timeframe_value", sa.String(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_condition_sets_user_id"), "condition_sets", ["user_id"], unique=False
    )
    op.drop_index(op.f("ix_symbols_isin"), table_name="symbols")
    op.drop_index(op.f("ix_symbols_market"), table_name="symbols")
    op.drop_index(op.f("ix_symbols_name"), table_name="symbols")
    op.drop_index(
        op.f("ix_symbols_search_vector_gin"),
        table_name="symbols",
        postgresql_using="gin",
    )
    op.drop_index(op.f("ix_symbols_ticker"), table_name="symbols")
    op.drop_index(op.f("ix_symbols_type"), table_name="symbols")
    op.drop_table("symbols")
    op.drop_index(op.f("ix_scans_user_id"), table_name="scans")
    op.drop_table("scans")
    op.add_column(
        "lists",
        sa.Column(
            "columns",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("lists", "columns")
    op.create_table(
        "scans",
        sa.Column("user_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "conditions",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "conditional_logic", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "columns",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("source", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["source"], ["lists.id"], name=op.f("scans_source_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("scans_pkey")),
    )
    op.create_index(op.f("ix_scans_user_id"), "scans", ["user_id"], unique=False)
    op.create_table(
        "symbols",
        sa.Column("ticker", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("type", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("market", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("isin", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "indexes",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "typespecs",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "search_vector",
            postgresql.TSVECTOR(),
            sa.Computed(
                "to_tsvector('english'::regconfig, (((ticker)::text || ' '::text) || (name)::text))",
                persisted=True,
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("symbols_pkey")),
    )
    op.create_index(op.f("ix_symbols_type"), "symbols", ["type"], unique=False)
    op.create_index(op.f("ix_symbols_ticker"), "symbols", ["ticker"], unique=True)
    op.create_index(
        op.f("ix_symbols_search_vector_gin"),
        "symbols",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(op.f("ix_symbols_name"), "symbols", ["name"], unique=False)
    op.create_index(op.f("ix_symbols_market"), "symbols", ["market"], unique=False)
    op.create_index(op.f("ix_symbols_isin"), "symbols", ["isin"], unique=False)
    op.drop_index(op.f("ix_condition_sets_user_id"), table_name="condition_sets")
    op.drop_table("condition_sets")
    # ### end Alembic commands ###
