"""rename_scan_sources_to_source

Revision ID: f865320e648b
Revises: 4d7b4c9f1c67
Create Date: 2026-02-20 20:35:23.051516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f865320e648b'
down_revision: Union[str, Sequence[str], None] = '4d7b4c9f1c67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scans', sa.Column('source', sa.String(), nullable=True))
    op.drop_constraint(op.f('scans_sources_fkey'), 'scans', type_='foreignkey')
    op.create_foreign_key(None, 'scans', 'lists', ['source'], ['id'])
    op.drop_column('scans', 'sources')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scans', sa.Column('sources', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'scans', type_='foreignkey')
    op.create_foreign_key(op.f('scans_sources_fkey'), 'scans', 'lists', ['sources'], ['id'])
    op.drop_column('scans', 'source')
    # ### end Alembic commands ###
