name: Build Docker
on:
  push:
    branches:
      - main
jobs:
  build_amd64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set outputs
        id: vars
        run: echo "::set-output name=short_commit_id::$(git rev-parse --short HEAD)"

      - name: Print Short Commit ID
        run: echo "${{ steps.vars.outputs.short_commit_id }}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: devfarmaan/terminal:latest-amd64,devfarmaan/terminal:${{steps.vars.outputs.short_commit_id}}-amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64

  build_arm64:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set outputs
        id: vars
        run: echo "::set-output name=short_commit_id::$(git rev-parse --short HEAD)"

      - name: Print Short Commit ID
        run: echo "${{ steps.vars.outputs.short_commit_id }}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: devfarmaan/terminal:latest-arm64,devfarmaan/terminal:${{steps.vars.outputs.short_commit_id}}-arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/arm64

  manifest:
    needs: [ build_amd64, build_arm64 ]
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create and push multi-arch manifest
        run: |
          docker manifest create devfarmaan/terminal:latest \
            --amend devfarmaan/terminal:latest-amd64 \
            --amend devfarmaan/terminal:latest-arm64

          docker manifest push devfarmaan/terminal:latest

          docker manifest create devfarmaan/terminal:${{ needs.set-vars.outputs.short_commit_id }} \
            --amend devfarmaan/terminal:${{ needs.set-vars.outputs.short_commit_id }}-amd64 \
            --amend devfarmaan/terminal:${{ needs.set-vars.outputs.short_commit_id }}-arm64

          docker manifest push devfarmaan/terminal:${{ needs.set-vars.outputs.short_commit_id }}