name: Build Docker

on:
  push:
    branches:
      - main

jobs:
  set-vars:
    runs-on: ubuntu-latest
    outputs:
      short_commit_id: ${{ steps.vars.outputs.short_commit_id }}
    steps:
      - uses: actions/checkout@v4

      - id: vars
        run: echo "short_commit_id=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

  build_amd64:
    needs: set-vars
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3
        with:
          install: true
          driver-opts: image=moby/buildkit:latest

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            devfarmaan/terminal:latest-amd64
            devfarmaan/terminal:${{ needs.set-vars.outputs.short_commit_id }}-amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64

  build_arm64:
    needs: set-vars
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3
        with:
          install: true
          driver-opts: image=moby/buildkit:latest

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            devfarmaan/terminal:latest-arm64
            devfarmaan/terminal:${{ needs.set-vars.outputs.short_commit_id }}-arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/arm64

  manifest:
    needs: [build_amd64, build_arm64, set-vars]
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create and push multi-arch manifest
        run: |
          docker manifest create devfarmaan/terminal:latest \
            --amend devfarmaan/terminal:latest-amd64 \
            --amend devfarmaan/terminal:latest-arm64

          docker manifest push devfarmaan/terminal:latest

          docker manifest create devfarmaan/terminal:${{ needs.set-vars.outputs.short_commit_id }} \
            --amend devfarmaan/terminal:${{ needs.set-vars.outputs.short_commit_id }}-amd64 \
            --amend devfarmaan/terminal:${{ needs.set-vars.outputs.short_commit_id }}-arm64

          docker manifest push devfarmaan/terminal:${{ needs.set-vars.outputs.short_commit_id }}